### ISSUE TITLE
Missing seeds per treatment info

### ISSUE THREAD

**Issue by scelmendorf** [G-TREE/DataSynthesisWorkshop#5]
- [ ] So far I cannot find the seeds added per treatment for Mt Hotham Transect 2.

**Comment by cbrownGTREE** [comment]
Do you mean seeds per plot? It is 100 seeds per plot for Mt. Hotham, all transects.

**Comment by cbrownGTREE** [comment]
I have updated in my GTREE_Data_MASTER_24March2017.xlsx, which I will upload this morning.
