### ISSUE TITLE
Cannot find the correct germination rates

### ISSUE THREAD

**Issue by scelmendorf** [G-TREE/DataSynthesisWorkshop#6]
- [ ] THERE IS NO DATA ON SEEDS ADDED OR GERM RATES FOR Picea glauca, AT, Wolf Creek, transect 2.3

- [ ] CHURCHILL - There are 2 values for germination success for the same species, seeding year, provenance & transect.  I don't know which one to use and wonder if this was a copy paste error.

**Comment by cbrownGTREE** [comment]
All of those are from Steve's data, which was confusing to merge with the rest, as I recall. I'll dig into his files (or @atrant - maybe you remember because we spent those hours on Skype pouring over them) and try and figure this out Monday.

**Comment by cbrownGTREE** [comment]
Re: Churchill. That is incredibly confusing (the data). I dug into Steve's revised files and there should be two different seeding years. I have corrected this in the site data sheet of GTREE_Data_MASTER_24March2017.xlsx to be uploaded this morning.

**Comment by cbrownGTREE** [comment]
After a lot of detective work, this appears to be a species name data entry error. Transect 2.3 in AT at Wolf Creek was seeded with Pinus contorta. GTREE_Data_MASTER_24March2017.xlsx updated accordingly.
